### PR TITLE
editing priors.py to ensure comapitbility with new bilby

### PR DESCRIPTION
**Pull request by rowina-n**
commenting line 34 in priors.py because it doesn't work with the latest version of bilby

### CODE REVIEW

**Comment by rowina-n** [comment]
@GregoryAshton Could you please merge this? I am nervous to

**Comment by GregoryAshton** [comment]
@rowina-n, rather than just commenting it out, can you delete the entire line? This saves having lots of commented-out code that we do not need.

Best,

Greg

**Comment by rowina-n** [comment]
Hey @GregoryAshton, I deleted the line as you requested

**Comment by GregoryAshton** [comment]
Great, thanks Rowina!

**Pull request merged**
